name: wbgwebsite

# 触发条件
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

# workflow 的具体内容
jobs:
  deploy:
    # 使用 Ubuntu 容器
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. 缓存 Python 包以加快后续运行
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      # 4. 安装 MkDocs Material
      - name: Install MkDocs Material
        run: pip install mkdocs-material

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
